import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'en' | 'zh-CN' | 'zh-TW';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageStore>()(
  persist(
    (set) => ({
      language: 'en',
      setLanguage: (language) => set({ language }),
    }),
    {
      name: 'erp-language',
    }
  )
);

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    products: 'Products',
    orders: 'Orders',
    customers: 'Customers',
    inventory: 'Inventory',

    // Dashboard
    welcomeBack: "Welcome back! Here's your business overview.",
    totalRevenue: 'Total Revenue',
    totalOrders: 'Total Orders',
    totalProducts: 'Total Products',
    totalCustomers: 'Total Customers',
    quickActions: 'Quick Actions',
    recentOrders: 'Recent Orders',
    viewAll: 'View All',
    vsLastMonth: 'vs last month',

    // Products
    manageProductInventory: 'Manage your product inventory',
    addProduct: 'Add Product',
    searchProducts: 'Search products...',
    allCategories: 'All Categories',
    product: 'Product',
    category: 'Category',
    price: 'Price',
    stock: 'Stock',
    status: 'Status',
    actions: 'Actions',
    active: 'Active',
    inactive: 'Inactive',
    units: 'units',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    productName: 'Product Name',
    description: 'Description',
    imageUrl: 'Image URL',

    // Orders
    manageCustomerOrders: 'Manage customer orders',
    newOrder: 'New Order',
    searchOrders: 'Search orders...',
    allStatuses: 'All Statuses',
    customer: 'Customer',
    items: 'Items',
    total: 'Total',
    date: 'Date',
    orderId: 'Order ID',
    pending: 'Pending',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    editOrder: 'Edit Order',
    createOrder: 'Create Order',
    selectCustomer: 'Select a customer',
    selectProduct: 'Select a product',
    quantity: 'Quantity',
    quantitiesHelp: 'comma-separated (e.g., 1,2,1)',

    // Customers
    manageCustomerDatabase: 'Manage your customer database',
    addCustomer: 'Add Customer',
    searchCustomers: 'Search customers...',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    orderCount: 'Orders',
    totalSpent: 'Total Spent',
    editCustomer: 'Edit Customer',

    // Inventory
    manageStockLevels: 'Manage stock levels and inventory',
    adjustStock: 'Adjust Stock',
    totalStock: 'Total Stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    allProducts: 'All Products',
    currentStock: 'Current Stock',
    inStock: 'In Stock',
    stockHistory: 'Stock History',
    quantityChange: 'Quantity Change',
    reason: 'Reason',
    selectProductOption: 'Select a product',
    quantityChangeHelp: 'Use positive for add, negative for remove',
    adjustStockTitle: 'Adjust Stock',
    stockAdded: 'Stock added',
    stockRemoved: 'Stock removed',

    // AI Assistant
    aiAssistant: 'AI Assistant',
    askMeAnything: 'Ask me anything...',
    thinking: 'Thinking...',
    help: 'Available Commands',
    showProducts: 'Show products',
    showOrders: 'Show orders',
    showCustomers: 'Show customers',
    revenueReport: 'Revenue report',
    dashboardSummary: 'Dashboard summary',
    lowStockProducts: 'Low stock products',
    topSellingProducts: 'Top selling products',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    update: 'Update',
    close: 'Close',
    confirm: 'Confirm',
    success: 'Success',
    error: 'Error',

    // Notifications
    productAdded: 'Product added successfully!',
    productUpdated: 'Product updated successfully!',
    productDeleted: 'Product deleted successfully!',
    customerAdded: 'Customer added successfully!',
    customerUpdated: 'Customer updated successfully!',
    customerDeleted: 'Customer deleted successfully!',
    orderCreated: 'Order created successfully!',
    orderUpdated: 'Order updated successfully!',
    orderDeleted: 'Order deleted successfully!',
    orderStatusUpdated: 'Order status updated to',
    stockAdjusted: 'Stock adjusted successfully!',

    // Language
    language: 'Language',
    english: 'English',
    simplifiedChinese: '简体中文',
    traditionalChinese: '繁體中文',

    // AI Models
    aiModels: 'AI Models',
    chatModel: 'Chat Model',
    voiceModel: 'Voice/STT Model',
    apiKey: 'API Key',
    baseURL: 'Base URL',
    modelName: 'Model Name',
    testConnection: 'Test Connection',
    connectionSuccess: 'Connection successful!',
    connectionFailed: 'Connection failed',
  },

  'zh-CN': {
    // Navigation
    dashboard: '仪表盘',
    products: '产品',
    orders: '订单',
    customers: '客户',
    inventory: '库存',

    // Dashboard
    welcomeBack: '欢迎回来！这是您的业务概览。',
    totalRevenue: '总收入',
    totalOrders: '总订单',
    totalProducts: '总产品',
    totalCustomers: '总客户',
    quickActions: '快捷操作',
    recentOrders: '最近订单',
    viewAll: '查看全部',
    vsLastMonth: '较上月',

    // Products
    manageProductInventory: '管理您的产品库存',
    addProduct: '添加产品',
    searchProducts: '搜索产品...',
    allCategories: '所有分类',
    product: '产品',
    category: '分类',
    price: '价格',
    stock: '库存',
    status: '状态',
    actions: '操作',
    active: '启用',
    inactive: '停用',
    units: '件',
    editProduct: '编辑产品',
    deleteProduct: '删除产品',
    productName: '产品名称',
    description: '描述',
    imageUrl: '图片链接',

    // Orders
    manageCustomerOrders: '管理客户订单',
    newOrder: '新建订单',
    searchOrders: '搜索订单...',
    allStatuses: '所有状态',
    customer: '客户',
    items: '商品',
    total: '总计',
    date: '日期',
    orderId: '订单号',
    pending: '待处理',
    processing: '处理中',
    shipped: '已发货',
    delivered: '已送达',
    cancelled: '已取消',
    editOrder: '编辑订单',
    createOrder: '创建订单',
    selectCustomer: '选择客户',
    selectProduct: '选择产品',
    quantity: '数量',
    quantitiesHelp: '用逗号分隔（例如：1,2,1）',

    // Customers
    manageCustomerDatabase: '管理您的客户数据库',
    addCustomer: '添加客户',
    searchCustomers: '搜索客户...',
    fullName: '姓名',
    email: '邮箱',
    phone: '电话',
    address: '地址',
    orderCount: '订单数',
    totalSpent: '消费总额',
    editCustomer: '编辑客户',

    // Inventory
    manageStockLevels: '管理库存水平',
    adjustStock: '调整库存',
    totalStock: '总库存',
    lowStock: '低库存',
    outOfStock: '缺货',
    allProducts: '所有产品',
    currentStock: '当前库存',
    inStock: '有货',
    stockHistory: '库存历史',
    quantityChange: '数量变化',
    reason: '原因',
    selectProductOption: '选择产品',
    quantityChangeHelp: '正数增加，负数减少',
    adjustStockTitle: '调整库存',
    stockAdded: '库存已添加',
    stockRemoved: '库存已减少',

    // AI Assistant
    aiAssistant: 'AI 助手',
    askMeAnything: '问我任何问题...',
    thinking: '思考中...',
    help: '可用命令',
    showProducts: '显示产品',
    showOrders: '显示订单',
    showCustomers: '显示客户',
    revenueReport: '营收报告',
    dashboardSummary: '仪表盘摘要',
    lowStockProducts: '低库存产品',
    topSellingProducts: '畅销产品',

    // Common
    save: '保存',
    cancel: '取消',
    add: '添加',
    edit: '编辑',
    delete: '删除',
    update: '更新',
    close: '关闭',
    confirm: '确认',
    success: '成功',
    error: '错误',

    // Notifications
    productAdded: '产品添加成功！',
    productUpdated: '产品更新成功！',
    productDeleted: '产品删除成功！',
    customerAdded: '客户添加成功！',
    customerUpdated: '客户更新成功！',
    customerDeleted: '客户删除成功！',
    orderCreated: '订单创建成功！',
    orderUpdated: '订单更新成功！',
    orderDeleted: '订单删除成功！',
    orderStatusUpdated: '订单状态已更新为',
    stockAdjusted: '库存调整成功！',

    // Language
    language: '语言',
    english: 'English',
    simplifiedChinese: '简体中文',
    traditionalChinese: '繁體中文',

    // AI Models
    aiModels: 'AI 模型',
    chatModel: '聊天模型',
    voiceModel: '语音识别模型',
    apiKey: 'API 密钥',
    baseURL: 'Base URL',
    modelName: '模型名称',
    testConnection: '测试连接',
    connectionSuccess: '连接成功！',
    connectionFailed: '连接失败',
  },

  'zh-TW': {
    // Navigation
    dashboard: '儀表板',
    products: '產品',
    orders: '訂單',
    customers: '客戶',
    inventory: '庫存',

    // Dashboard
    welcomeBack: '歡迎回來！這是您的業務概覽。',
    totalRevenue: '總收入',
    totalOrders: '總訂單',
    totalProducts: '總產品',
    totalCustomers: '總客戶',
    quickActions: '快捷操作',
    recentOrders: '最近訂單',
    viewAll: '查看全部',
    vsLastMonth: '較上月',

    // Products
    manageProductInventory: '管理您的產品庫存',
    addProduct: '新增產品',
    searchProducts: '搜尋產品...',
    allCategories: '所有分類',
    product: '產品',
    category: '分類',
    price: '價格',
    stock: '庫存',
    status: '狀態',
    actions: '操作',
    active: '啟用',
    inactive: '停用',
    units: '件',
    editProduct: '編輯產品',
    deleteProduct: '刪除產品',
    productName: '產品名稱',
    description: '描述',
    imageUrl: '圖片連結',

    // Orders
    manageCustomerOrders: '管理客戶訂單',
    newOrder: '新建訂單',
    searchOrders: '搜尋訂單...',
    allStatuses: '所有狀態',
    customer: '客戶',
    items: '商品',
    total: '總計',
    date: '日期',
    orderId: '訂單號',
    pending: '待處理',
    processing: '處理中',
    shipped: '已發貨',
    delivered: '已送達',
    cancelled: '已取消',
    editOrder: '編輯訂單',
    createOrder: '建立訂單',
    selectCustomer: '選擇客戶',
    selectProduct: '選擇產品',
    quantity: '數量',
    quantitiesHelp: '用逗號分隔（例如：1,2,1）',

    // Customers
    manageCustomerDatabase: '管理您的客戶資料庫',
    addCustomer: '新增客戶',
    searchCustomers: '搜尋客戶...',
    fullName: '姓名',
    email: '電子郵件',
    phone: '電話',
    address: '地址',
    orderCount: '訂單數',
    totalSpent: '消費總額',
    editCustomer: '編輯客戶',

    // Inventory
    manageStockLevels: '管理庫存水平',
    adjustStock: '調整庫存',
    totalStock: '總庫存',
    lowStock: '低庫存',
    outOfStock: '缺貨',
    allProducts: '所有產品',
    currentStock: '目前庫存',
    inStock: '有貨',
    stockHistory: '庫存歷史',
    quantityChange: '數量變化',
    reason: '原因',
    selectProductOption: '選擇產品',
    quantityChangeHelp: '正數增加，負數減少',
    adjustStockTitle: '調整庫存',
    stockAdded: '庫存已添加',
    stockRemoved: '庫存已減少',

    // AI Assistant
    aiAssistant: 'AI 助手',
    askMeAnything: '問我任何問題...',
    thinking: '思考中...',
    help: '可用指令',
    showProducts: '顯示產品',
    showOrders: '顯示訂單',
    showCustomers: '顯示客戶',
    revenueReport: '營收報告',
    dashboardSummary: '儀表板摘要',
    lowStockProducts: '低庫存產品',
    topSellingProducts: '暢銷產品',

    // Common
    save: '儲存',
    cancel: '取消',
    add: '新增',
    edit: '編輯',
    delete: '刪除',
    update: '更新',
    close: '關閉',
    confirm: '確認',
    success: '成功',
    error: '錯誤',

    // Notifications
    productAdded: '產品新增成功！',
    productUpdated: '產品更新成功！',
    productDeleted: '產品刪除成功！',
    customerAdded: '客戶新增成功！',
    customerUpdated: '客戶更新成功！',
    customerDeleted: '客戶刪除成功！',
    orderCreated: '訂單建立成功！',
    orderUpdated: '訂單更新成功！',
    orderDeleted: '訂單刪除成功！',
    orderStatusUpdated: '訂單狀態已更新為',
    stockAdjusted: '庫存調整成功！',

    // Language
    language: '語言',
    english: 'English',
    simplifiedChinese: '简体中文',
    traditionalChinese: '繁體中文',

    // AI Models
    aiModels: 'AI 模型',
    chatModel: '聊天模型',
    voiceModel: '語音識別模型',
    apiKey: 'API 密鑰',
    baseURL: 'Base URL',
    modelName: '模型名稱',
    testConnection: '測試連接',
    connectionSuccess: '連接成功！',
    connectionFailed: '連接失敗',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
